# Site settings
title: 台灣機車環島 - 秋天騎士
topic_title: 台灣機車環島
baseurl: '/taiwan' # the subpath of your site, e.g. /blog
url: 'https://autumnal-rider.github.io' # the base hostname & protocol for your site
siteurl: 'https://autumnal-rider.github.io/taiwan'
lang: zh
author: '秋天騎士'
travel:
  instrument_type: 'https://auto.schema.org/Motorcycle'

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink: "/:year/:month/:day/:title/"

pagination:          false

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

data:
  social:
    disqus_shortname: autumnal-rider

jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options